#ifndef CONSTANTS_H
#define CONSTANTS_H

#define GPLAYBACK_OP_INSERT_WORD_AFTER 1
#define GPLAYBACK_OP_INSERT_ROW_AFTER 2
#define GPLAYBACK_OP_DELETE_WORDS 3
#define GPLAYBACK_OP_DELETE_ROWS 4
#define GPLAYBACK_OP_MOVE_ROWS 5
#define GPLAYBACK_OP_CONCAT_ROWS 6
#define GPLAYBACK_OP_SPLIT_ROWS 7
#define GPLAYBACK_OP_INSERT_WORD_BEFORE 8
#define GPLAYBACK_OP_INSERT_ROW_BEFORE 9
#define GPLAYBACK_OP_CUT_WORDS 10
#define GPLAYBACK_OP_PASTE_WORDS 11

#define GPLAYBACK_REPLACE_SIM_ENTROPY 1.5
#define GPLAYBACK_REPLACE_SIM_TRESHOLD 0.25

#define GPLAYBACK_TOKEN_NEWLINE '\n'
#define GPLAYBACK_TOKEN_SPACE ' '
#define GPLAYBACK_TOKEN_TAB '\t'
#define GPLAYBACK_TOKEN_NEVER '\xff'

#endif /* CONSTANTS_H */
